enum Constants {
  EXAM_GET_ALL_REQUEST = 'EXAM_GET_ALL_REQUEST',
  EXAM_GET_ALL_ERROR = 'EXAM_GET_ALL_ERROR',
  EXAM_GET_ALL_SUCCESS = 'EXAM_GET_ALL_SUCCESS',

  EXAM_HANDLE_MODAL = 'EXAM_HANDLE_MODAL',

  EXAM_CREATE_REQUEST = 'EXAM_CREATE_REQUEST',
  EXAM_CREATE_ERROR = 'EXAM_CREATE_ERROR',
  EXAM_CREATE_SUCCESS = 'EXAM_CREATE_SUCCESS',
}

export default Constants;
