enum Constants {
  EXAM_GET_ALL_REQUEST = 'EXAM_GET_ALL_REQUEST',
  EXAM_GET_ALL_ERROR = 'EXAM_GET_ALL_ERROR',
  EXAM_GET_ALL_SUCCESS = 'EXAM_GET_ALL_SUCCESS',

  EXAM_GET_ONE_REQUEST = 'EXAM_GET_ONE_REQUEST',
  EXAM_GET_ONE_ERROR = 'EXAM_GET_ONE_ERROR',
  EXAM_GET_ONE_SUCCESS = 'EXAM_GET_ONE_SUCCESS',

  EXAM_DELETE_REQUEST = 'EXAM_DELETE_REQUEST',
  EXAM_DELETE_ERROR = 'EXAM_DELETE_ERROR',
  EXAM_DELETE_SUCCESS = 'EXAM_DELETE_SUCCESS',

  EXAM_GET_RESPONSES_REQUEST = 'EXAM_GET_RESPONSES_REQUEST',
  EXAM_GET_RESPONSES_ERROR = 'EXAM_GET_RESPONSES_ERROR',
  EXAM_GET_RESPONSES_SUCCESS = 'EXAM_GET_RESPONSES_SUCCESS',

  EXAM_HANDLE_MODAL = 'EXAM_HANDLE_MODAL',

  EXAM_CREATE_REQUEST = 'EXAM_CREATE_REQUEST',
  EXAM_CREATE_ERROR = 'EXAM_CREATE_ERROR',
  EXAM_CREATE_SUCCESS = 'EXAM_CREATE_SUCCESS',

  EXAM_HANDLE_NEXT_PREVIOUS = 'EXAM_HANDLE_NEXT_PREVIOUS',
}

export default Constants;
