enum Constants {
  AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS',

  AUTHENTICATION_UPDATE_PROFILE_REQUEST = 'AUTHENTICATION_UPDATE_PROFILE_REQUEST',
  AUTHENTICATION_UPDATE_PROFILE_ERROR = 'AUTHENTICATION_UPDATE_PROFILE_ERROR',
  AUTHENTICATION_UPDATE_PROFILE_SUCCESS = 'AUTHENTICATION_UPDATE_PROFILE_SUCCESS',

  AUTHENTICATION_LOGOUT_REQUEST = 'AUTHENTICATION_LOGOUT_REQUEST',
}

export default Constants;
